<%@ Page Title="HTML Comments" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="ContentH12.aspx.cs" Inherits="ContentH12" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
    <h2>HTML Comments</h2>
    <p>Comment tags <!-- and --> are used to insert comments in HTML.</p>
    <h3>HTML Comment Tags</h3>
    <p>You can add comments to your HTML source by using the following syntax:</p>
    &lt;!-- Write your comments here --&gt;
    <p><b>Note</b>: There is an exclamation point (!) in the opening tag, but not in the closing tag.</p>
   <p>Comments are not displayed by the browser, but they can help document your HTML.

With comments you can place notifications and reminders in your HTML:</p>
    &lt;!-- This is a comment --&gt;<br />

&lt;p&gt;This is a paragraph.&lt;/p&gt;<br />

&lt;!-- Remember to add more information here --&gt;<br />

<p>Comments are also great for debugging HTML, because you can comment out HTML lines of code, one at a time, to search for errors:</p>
&lt;!-- Do not display this at the moment
&lt;img border="0" src="pic_mountain.jpg" alt="Mountain"&gt;
--&gt;
    <h3>Conditional Comments</h3>
    <p>You might stumble upon conditional comments in HTML:</p>
    &lt;!--[if IE 8]&gt;<br />
    .... some HTML here ....<br />
&lt;![endif]--&gt;
    <h3>Software Program Tags</h3>
    <p>HTML comments tags can also be generated by various HTML software programs.

For example &lt;!--webbot bot--&gt; tags wrapped inside HTML comments by FrontPage and Expression Web.

As a rule, let these tags stay, to help support the software that created them.</p>


</asp:Content>

